# Generated by Django 6.0.6 on 2026-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_quote_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
